version: "3.3"
services:
    image-roc5:
        build: .
        volumes:
           - ./Stable-diffusion:/xdocker/stable-diffusion-webui/models/Stable-diffusion
           - ./logs:/xdocker/stable-diffusion-webui/logs
           - ./outputs:/xdocker/stable-diffusion-webui/outputs
        network_mode:
           host
        devices:
           - /dev/kfd
           - /dev/dri
        ipc: host
